2015/09/17 14:42:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "enviarArchivosPorCorreo".' in C:\xampp\htdocs\faylinnpole\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\faylinnpole\framework\web\CWebApplication.php(141): CWebApplication->runController('enviarArchivosP...')
#1 C:\xampp\htdocs\faylinnpole\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\faylinnpole\faylinn\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/faylinnpole/faylinn/enviarArchivosPorCorreo
HTTP_REFERER=http://localhost/faylinnpole/faylinn/
---
2015/09/17 14:42:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "enviarArchivosPorCorreo".' in C:\xampp\htdocs\faylinnpole\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\faylinnpole\framework\web\CWebApplication.php(141): CWebApplication->runController('enviarArchivosP...')
#1 C:\xampp\htdocs\faylinnpole\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\faylinnpole\faylinn\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/faylinnpole/faylinn/enviarArchivosPorCorreo
HTTP_REFERER=http://localhost/faylinnpole/faylinn/
---
2015/09/17 14:44:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "enviarCorreo".' in C:\xampp\htdocs\faylinnpole\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\faylinnpole\framework\web\CController.php(270): CController->missingAction('enviarCorreo')
#1 C:\xampp\htdocs\faylinnpole\framework\web\CWebApplication.php(282): CController->run('enviarCorreo')
#2 C:\xampp\htdocs\faylinnpole\framework\web\CWebApplication.php(141): CWebApplication->runController('site/enviarCorr...')
#3 C:\xampp\htdocs\faylinnpole\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\faylinnpole\faylinn\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/faylinnpole/faylinn/site/enviarCorreo
HTTP_REFERER=http://localhost/faylinnpole/faylinn/
---
2015/09/17 14:44:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "enviarCsdfsdfsorreo".' in C:\xampp\htdocs\faylinnpole\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\faylinnpole\framework\web\CController.php(270): CController->missingAction('enviarCsdfsdfso...')
#1 C:\xampp\htdocs\faylinnpole\framework\web\CWebApplication.php(282): CController->run('enviarCsdfsdfso...')
#2 C:\xampp\htdocs\faylinnpole\framework\web\CWebApplication.php(141): CWebApplication->runController('site/enviarCsdf...')
#3 C:\xampp\htdocs\faylinnpole\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\faylinnpole\faylinn\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/faylinnpole/faylinn/site/enviarCsdfsdfsorreo
---
2015/09/17 14:45:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "enviarCsdfsdfsorreo".' in C:\xampp\htdocs\faylinnpole\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\faylinnpole\framework\web\CController.php(270): CController->missingAction('enviarCsdfsdfso...')
#1 C:\xampp\htdocs\faylinnpole\framework\web\CWebApplication.php(282): CController->run('enviarCsdfsdfso...')
#2 C:\xampp\htdocs\faylinnpole\framework\web\CWebApplication.php(141): CWebApplication->runController('site/enviarCsdf...')
#3 C:\xampp\htdocs\faylinnpole\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\faylinnpole\faylinn\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/faylinnpole/faylinn/site/enviarCsdfsdfsorreo
---
2015/09/17 14:45:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "enviarCorreo".' in C:\xampp\htdocs\faylinnpole\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\faylinnpole\framework\web\CController.php(270): CController->missingAction('enviarCorreo')
#1 C:\xampp\htdocs\faylinnpole\framework\web\CWebApplication.php(282): CController->run('enviarCorreo')
#2 C:\xampp\htdocs\faylinnpole\framework\web\CWebApplication.php(141): CWebApplication->runController('site/enviarCorr...')
#3 C:\xampp\htdocs\faylinnpole\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\faylinnpole\faylinn\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/faylinnpole/faylinn/site/enviarCorreo
HTTP_REFERER=http://localhost/faylinnpole/faylinn/site/enviarCsdfsdfsorreo
---
2015/09/17 14:47:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "enviarArchivosPorCorreo".' in C:\xampp\htdocs\faylinnpole\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\faylinnpole\framework\web\CWebApplication.php(141): CWebApplication->runController('enviarArchivosP...')
#1 C:\xampp\htdocs\faylinnpole\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\faylinnpole\faylinn\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/faylinnpole/faylinn/enviarArchivosPorCorreo
HTTP_REFERER=http://localhost/faylinnpole/faylinn/
---
2015/09/17 14:48:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "enviarCorreo".' in C:\xampp\htdocs\faylinnpole\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\faylinnpole\framework\web\CWebApplication.php(141): CWebApplication->runController('enviarCorreo')
#1 C:\xampp\htdocs\faylinnpole\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\faylinnpole\faylinn\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/faylinnpole/faylinn/enviarCorreo
HTTP_REFERER=http://localhost/faylinnpole/faylinn/
---
2015/09/17 14:48:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "enviarCorreo".' in C:\xampp\htdocs\faylinnpole\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\faylinnpole\framework\web\CWebApplication.php(141): CWebApplication->runController('enviarCorreo')
#1 C:\xampp\htdocs\faylinnpole\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\faylinnpole\faylinn\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/faylinnpole/faylinn/enviarCorreo
---
2015/09/17 14:48:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "enviarCorreo".' in C:\xampp\htdocs\faylinnpole\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\faylinnpole\framework\web\CWebApplication.php(141): CWebApplication->runController('enviarCorreo')
#1 C:\xampp\htdocs\faylinnpole\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\faylinnpole\faylinn\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/faylinnpole/faylinn/enviarCorreo
---
2015/09/17 14:48:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "enviarCorreo".' in C:\xampp\htdocs\faylinnpole\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\faylinnpole\framework\web\CWebApplication.php(141): CWebApplication->runController('enviarCorreo')
#1 C:\xampp\htdocs\faylinnpole\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\faylinnpole\faylinn\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/faylinnpole/faylinn/enviarCorreo
---
2015/09/17 14:49:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "enviarCorreo".' in C:\xampp\htdocs\faylinnpole\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\faylinnpole\framework\web\CWebApplication.php(141): CWebApplication->runController('enviarCorreo')
#1 C:\xampp\htdocs\faylinnpole\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\faylinnpole\faylinn\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/faylinnpole/faylinn/enviarCorreo
---
2015/09/17 14:49:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "enviarCorreo".' in C:\xampp\htdocs\faylinnpole\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\faylinnpole\framework\web\CWebApplication.php(141): CWebApplication->runController('enviarCorreo')
#1 C:\xampp\htdocs\faylinnpole\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\faylinnpole\faylinn\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/faylinnpole/faylinn/enviarCorreo
---
2015/09/17 14:49:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "enviarCorreo".' in C:\xampp\htdocs\faylinnpole\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\faylinnpole\framework\web\CWebApplication.php(141): CWebApplication->runController('enviarCorreo')
#1 C:\xampp\htdocs\faylinnpole\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\faylinnpole\faylinn\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/faylinnpole/faylinn/enviarCorreo
---
2015/09/17 16:15:46 [error] [exception.CException] exception 'CException' with message 'View "application.views.layouts.mail" does not exist!' in C:\xampp\htdocs\faylinnpole\faylinn\protected\extensions\YiiMailer\YiiMailer.php:464
Stack trace:
#0 C:\xampp\htdocs\faylinnpole\faylinn\protected\extensions\YiiMailer\YiiMailer.php(498): YiiMailer->renderView('application.vie...', Array)
#1 C:\xampp\htdocs\faylinnpole\faylinn\protected\extensions\YiiMailer\YiiMailer.php(482): YiiMailer->MsgHTMLWithLayout('<h1>Nuevo comen...', 'C:/xampp/htdocs...')
#2 C:\xampp\htdocs\faylinnpole\faylinn\protected\extensions\YiiMailer\YiiMailer.php(508): YiiMailer->render()
#3 C:\xampp\htdocs\faylinnpole\faylinn\protected\controllers\SiteController.php(119): YiiMailer->send()
#4 C:\xampp\htdocs\faylinnpole\framework\web\actions\CInlineAction.php(49): SiteController->actionEnviarCorreo()
#5 C:\xampp\htdocs\faylinnpole\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 C:\xampp\htdocs\faylinnpole\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#7 C:\xampp\htdocs\faylinnpole\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\faylinnpole\framework\web\CWebApplication.php(282): CController->run('enviarCorreo')
#9 C:\xampp\htdocs\faylinnpole\framework\web\CWebApplication.php(141): CWebApplication->runController('site/enviarCorr...')
#10 C:\xampp\htdocs\faylinnpole\framework\base\CApplication.php(184): CWebApplication->processRequest()
#11 C:\xampp\htdocs\faylinnpole\faylinn\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/faylinnpole/faylinn/site/enviarCorreo
HTTP_REFERER=http://localhost/faylinnpole/faylinn/
---
2015/09/17 16:39:59 [error] [exception.CException] exception 'CException' with message 'SiteController cannot find the requested view "diana".' in C:\xampp\htdocs\faylinnpole\framework\web\CController.php:878
Stack trace:
#0 C:\xampp\htdocs\faylinnpole\framework\web\CController.php(782): CController->renderPartial('diana', NULL, true)
#1 C:\xampp\htdocs\faylinnpole\faylinn\protected\controllers\SiteController.php(130): CController->render('diana')
#2 C:\xampp\htdocs\faylinnpole\framework\web\actions\CInlineAction.php(49): SiteController->actionDiana()
#3 C:\xampp\htdocs\faylinnpole\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\faylinnpole\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\faylinnpole\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\htdocs\faylinnpole\framework\web\CWebApplication.php(282): CController->run('diana')
#7 C:\xampp\htdocs\faylinnpole\framework\web\CWebApplication.php(141): CWebApplication->runController('site/diana')
#8 C:\xampp\htdocs\faylinnpole\framework\base\CApplication.php(184): CWebApplication->processRequest()
#9 C:\xampp\htdocs\faylinnpole\faylinn\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/faylinnpole/faylinn/site/diana
HTTP_REFERER=http://localhost/faylinnpole/faylinn/site/index
---
2015/09/17 17:18:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "index2".' in C:\xampp\htdocs\faylinnpole\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\faylinnpole\framework\web\CWebApplication.php(141): CWebApplication->runController('index2')
#1 C:\xampp\htdocs\faylinnpole\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\faylinnpole\faylinn\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/faylinnpole/faylinn/index2
---
